export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS';
export const FETCH_CAMPAIGNS_SUCCESS = 'FETCH_CAMPAIGNS_SUCCESS';

export const FETCH_ACTIVE_CAMPAIGN = 'FETCH_ACTIVE_CAMPAIGN';
export const FETCH_ACTIVE_CAMPAIGN_SUCCESS = 'FETCH_ACTIVE_CAMPAIGN_SUCCESS';

export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const CREATE_CAMPAIGN_START = 'CREATE_CAMPAIGN_START';
export const CREATE_CAMPAIGN_SUCCESS = 'CREATE_CAMPAIGN_SUCCESS';
export const CREATE_CAMPAIGN_FAILED = 'CREATE_CAMPAIGN_FAILED';

export const CONTRIBUTE = 'CONTRIBUTE';
export const CONTRIBUTE_START = 'CONTRIBUTE_START';
export const CONTRIBUTE_SUCCESS = 'CONTRIBUTE_SUCCESS';
export const CONTRIBUTE_FAILED = 'CONTRIBUTE_FAILED';

export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const CREATE_REQUEST_START = 'CREATE_REQUEST_START';
export const CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS';
export const CREATE_REQUEST_FAILED = 'CREATE_REQUEST_FAILED';

export const APPROVE_REQUEST = 'APPROVE_REQUEST';
export const APPROVE_REQUEST_FAILED = 'APPROVE_REQUEST_FAILED';

export const FINALIZE_REQUEST = 'FINALIZE_REQUEST';
export const FINALIZE_REQUEST_FAILED = 'FINALIZE_REQUEST_FAILED';
